spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_crud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #??sql
    show-sql: true
    properties:
      hibernate:
        #???sql
        format_sql: true
server:
  port: 8181
